sudo: false
language: python
install: 
  - pip install pipenv --upgrade
  - pipenv run pip install pip==18
  - pipenv install --dev --skip-lock
cache: pip
python: 3.6
jobs:
  include:
    - stage: "Test"
      name: "mypy"
      script: pipenv run mypy algo/ tests/ bench/
    - stage: "Test"
      name: "pytest"
      script: pipenv run pytest
    - stage: "Test"
      name: "black"
      script: pipenv run black --check algo/ tests/ bench/
    - stage: "Test"
      name: "flake8"
      script: pipenv run flake8 algo/ test/ bench/

    - stage: "Coverage"
      name: "coverage"
      script: pipenv run pytest --cov
