sudo: false
language: python
install: 
        - pip install pipenv --upgrade
        - pipenv run pip install pip==18.0 
        - pipenv install --dev --skip-lock
cache: pip
script:
        - pipenv run pytest
python: 3.6
