sudo: false
language: python
install: 
        - pip install pipenv --upgrade
        - pipenv run pip install pip==18
        - pipenv install --dev --skip-lock
cache: pip
script:
        - pipenv run mypy algo/ tests/ bench/
        - pipenv run pytest
        - pipenv run black --check algo/ tests/ bench/
        - pipenv run flake8 algo/ test/ bench/
python: 3.6
