sudo: false
language: python
install: 
        - pip install pipenv --upgrade
        - pipenv run pip install pip==18.0 
        - pipenv install --dev --skip-lock
cache: pip
script:
        - pipenv run mypy algo/
        - pipenv run pytest
        - pipenv run black --check algo/
        - pipenv run flake8 algo/
python: 3.6
